### ISSUE TITLE
The Eased, Hindered and Quick Stat macros throw a MacroOnlyAppliesToPC error even if a token is selected. 

### ISSUE THREAD

**Issue by ClaudiaCarpenter** [mrkwnzl/cyphersystem-foundryvtt#366] opened 2024-07-15 20:44 UTC
Issue:
The Eased, Hindered and Quick Stat macros throw a MacroOnlyAppliesToPC error even if a token is selected.

Steps:
1. Click to select a token
2. Click one of the aforementioned macros
3. Click Roll
4. Observe the error message and that the roll does not occur

Expected:
The roll to happen

Using:
- Foundry 11 stable, build 315 (on forge-vtt)
- Cypher System 2.15.0
- Chrome 126.0.6478.127 (Official Build) (arm64)

----

Apologies in advance, as I'm new to GMing both in Foundry and with the Cypher system!

<img width="892" alt="Screenshot 2024-07-15 at 1 41 27 PM" src="https://github.com/user-attachments/assets/73860e48-9d22-4fe0-85c7-a2382f78b0a1">

**Comment by ClaudiaCarpenter** [comment] 2024-07-15 20:46
Sorry, I didn't capture the stat dialog popup!
<img width="887" alt="Screenshot 2024-07-15 at 1 46 41 PM" src="https://github.com/user-attachments/assets/64866fab-58fc-4076-9e09-2c4a7b5fa23d">

**Comment by mrkwnzl** [comment] 2024-07-16 05:49
Hey Claudia!

> Apologies in advance, as I'm new to GMing both in Foundry and with the Cypher system!

No worries! This stuff isn’t obvious at all and, to be honest, my documentation could be better. I’m always happy to help.

Regarding these macros, this is by design. Those macros are intended for players to make rolls for their default controlled actor. So in order to use them, you need to configure a controlled PC actor (other types won’t work) in the user configuration. See here for details, under “User Configuration”: https://foundryvtt.com/article/users/

The macros ignore selected tokens because some players can move various tokens and don’t remember to deselect them afterwards and then they’d make a roll for that token instead of their own character.

If you (or your players) really need to make a roll for a token (for example, to make a roll for an NPC or follower), you can use the Simplified Stat Roll macro, which will work on non-PC actors as well.

I hope this helps. Feel free to ask more questions if they arise.

As a sidenote, the error message should appear before the dialog, though. I’m going to fix that in a future update. Thank you!

**Comment by ClaudiaCarpenter** [comment] 2024-07-16 16:55
Thank you! So much to learn when transitioning from Roll20/DndBeyond.

**Comment by mrkwnzl** [comment] 2024-07-17 08:59
Feel free do join our Discord for quicker responses. There are a lot of helpful people there.

(But to be clear, asking here is absolutely fine as well.)

I’m closing this for now, but feel free to re-open if further questions arise about this.

**Closed by mrkwnzl** 2024-07-17 08:59 UTC
Labels: works as intended
