### ISSUE TITLE
[Bug] Cannot create Lasting Damage as the file does not exist

### ISSUE THREAD

**Issue by NiceTSY** [mrkwnzl/cyphersystem-foundryvtt#44] opened 2021-02-01 16:49 UTC
**Describe the bug**

It is currently not possible to create (or at least put a description, image, changing the name, etc.) a lasting damage item as the UI sheet does (apparently) not exist. 

**Steps to reproduce the behaviour**

1. Try to create a Lasting Damage item

**Screenshots**

![image](https://user-images.githubusercontent.com/38940602/106489896-8b11f480-64b5-11eb-8f76-3ae8bf3cc70e.png)
![image](https://user-images.githubusercontent.com/38940602/106489843-7d5c6f00-64b5-11eb-8672-f21be9140761.png)

**Setup:**

 - Cypher System Version: 1.12.0
 - Foundry VTT Version: 0.7.9
 - Native App/Browser: Self-hosted Foundry / All browser (Chrome, Safari, Firefox, Edge, Opera, Brave and I suppose the others)

**Additional context**

Tried to uninstall, install again the system same problem. Tried with and without any modules, still the problem.

**Comment by mrkwnzl** [comment] 2021-02-01 18:20
Hey! I can’t reproduce this. Everything seems to be working on my end, both when creating lasting damage on the sheet and when created as an item.

Could you try two things for me?

1. Can you confirm that the file `item-lasting Damage-sheet.html` is in the system directory of Foundry? You should find that at `\AppData\Local\FoundryVTT\Data\systems\cyphersystem\templates\item-lasting Damage-sheet.html` (Windows) or `~/Library/Application Support/FoundryVTT/Data/systems/cyphersystem/templates/item-lasting Damage-sheet.html` (macOS).

    One thing to look out for is whether “Damage” in the file name is capitalized. It’s not in the error message, but it should be.

2. In case the file is there and it’s an issue with case-sensitivity, can you create a Power Shift and see if that works? If it’s about the case-sensitivity, Power Shifts shouldn’t work either. If that works, it’s something different.

Thanks!

**Comment by NiceTSY** [comment] 2021-02-01 18:30
So I had a look at it.

1. The sheet is present in the folder on the server and the "Damage" is capitalised
![image](https://user-images.githubusercontent.com/38940602/106501288-3e351a80-64c3-11eb-98b5-bf864c91e48d.png)

2. You right Power shift does not work either
![image](https://user-images.githubusercontent.com/38940602/106501607-a71c9280-64c3-11eb-88cc-948b0f3a9234.png)
![image](https://user-images.githubusercontent.com/38940602/106501557-99670d00-64c3-11eb-8c5d-5cf42a23752b.png)

Putting them in full normal (non-capitalised) made it works
![image](https://user-images.githubusercontent.com/38940602/106501840-e3e88980-64c3-11eb-9967-ff9594e6b2d3.png)
![image](https://user-images.githubusercontent.com/38940602/106501869-ecd95b00-64c3-11eb-9263-35675eb0bf0e.png)

**Comment by mrkwnzl** [comment] 2021-02-01 18:41
All right! Thanks! So now we have to figure out why it’s searching for a lower case file name. Can you tell me about your setup? How are you hosting? What OS?

**Comment by mrkwnzl** [comment] 2021-02-01 19:25
I *think* v1.12.1 fixes this. Can you confirm that?

**Comment by RvdE** [comment] 2021-02-01 19:45
Only Windows doesn't care about lower-/upper case. Unix-based OS's, like FreeBSD, Linux, etc. do.
I'm running on FreeBSD myself and had similar issues with Power Shifts. I'll test 1.12.1 and report back if it works.

Thanks for your hard work... it's much appreciated.

**Comment by RvdE** [comment] 2021-02-01 19:50
Ok. The template for Power Shifts works now, but if I open a previously created one it cannot load the icon. It's looking for "power **S**hift.svg", but the filename is actually "power **s**hift.svg". Haven't looked into any other templates yet, but could be an issue there as well.

**Comment by mrkwnzl** [comment] 2021-02-01 20:03
> Only Windows doesn't care about lower-/upper case. Unix-based OS's, like FreeBSD, Linux, etc. do.
> I'm running on FreeBSD myself and had similar issues with Power Shifts. I'll test 1.12.1 and report back if it works.
> 
> Thanks for your hard work... it's much appreciated.

macOS doesn’t care either, unless you use a file system that does.

> Ok. The template for Power Shifts works now, but if I open a previously created one it cannot load the icon. It's looking for "power **S**hift.svg", but the filename is actually "power **s**hift.svg". Haven't looked into any other templates yet, but could be an issue there as well.

Thanks! Fixed as well in the next release. I’ll see if I can update the old ones to the correct file name.

**Comment by NiceTSY** [comment] 2021-02-01 20:16
So, as reported by @RvdE everything seems to work now. BTW, I am running on Debian.

Many thanks! :D

**Comment by mrkwnzl** [comment] 2021-02-01 20:54
1.12.2 should fix that as well. @RvdE Can you confirm that the images of the old Power Shifts now work?

**Comment by RvdE** [comment] 2021-02-01 22:31
> 1.12.2 should fix that as well. @RvdE Can you confirm that the images of the old Power Shifts now work?

It's fixed now. Thanks.

**Comment by mrkwnzl** [comment] 2021-02-02 06:11
> It's fixed now. Thanks.

Awesome! Thanks!

**Closed by mrkwnzl** 2021-02-02 06:11 UTC
Labels: bug
