### ISSUE TITLE
Resizable Character Sheet

### ISSUE THREAD

**Issue by cityofkeats** [mrkwnzl/cyphersystem-foundryvtt#141] opened 2021-06-26 20:26 UTC
**Is your feature request related to a problem? Please describe.**  
There is no problem, per se. I just think it would be nice to be able to drag and resize the character sheet.

**Describe the solution you'd like**  
The sheet is very horizontally efficient. It may even be beneficial to make it vertically scalable only, without horizontal scaling being an option (which I assume could break the layout once you get to extremes).

**Describe alternatives you've considered**  
.-.-.-.

**Setup**  
Cypher System Version: 1.18.3
Foundry VTT Version: 0.8.8  
Native App/Browser: Native (GM), Chrome & Firefox (players)  

**Additional context**  
.-.-.-.

**Comment by mrkwnzl** [comment] 2021-06-27 07:04
Thanks for the suggestion. The difficulty with that is the editor for the description, which does not play nicely with dynamic window sizes. And it’s indeed the height of the window that makes these problems (such as having two scroll bars when the description is getting too long).

Even the DnD5e system has this problem, which I consider the benchmark for questions like this. See this image:

<img width="830" alt="Bildschirmfoto 2021-06-27 um 08 34 38" src="https://user-images.githubusercontent.com/40534855/123535169-85e26a00-d722-11eb-82cd-2eca6106df5f.png">

I filled the text box with 35 lines, which I expect isn’t all that much, and two scroll bars appeared, which just isn’t good UX. What I could do is hard code the editor box, so that it doesn’t grow with the window size, but I’m sure I’m getting bug reports then, that the editor size is too small if you increase the window size. Not sure how I’d convey that this is expected behavior.

And it could only be used to increase the size from the default. You couldn’t make the window smaller. But I’m not sure whether you’d want to in- or decrease the window size. What would be your use case for that?

**Comment by cityofkeats** [comment] 2021-06-27 19:06
Largely, the use case is simply to have more real estate to view list items. This is just a plain, unexpanded view of items. When multiple items are expanded, the amount of scrolling increases dramatically. Obviously, the ability to expand the window vertically would only help so much.

![image](https://user-images.githubusercontent.com/72959678/123555952-6c571780-d74e-11eb-880b-3fc872d746c4.png)

An alternative solution would be the ability to mess with font size, row height, or icon size for expanded list items. It's difficult, though, because your sheet is already incredibly space efficient, and only got more efficient with the recent shrinking of the top sections. What about setting the sheet's height to a high percentage of window height (perhaps with a minimum height)?

What would happen if you set the .sheet-body height to 100% (leaving the other elements above it fixed pixel heights) with an adjustable window size?

**Comment by mrkwnzl** [comment] 2021-06-27 20:05
The problem isn’t that we couldn’t increase the height of the sheet body, it’s that the TinyMCE editor is not flexible enough. The only way I have found, and other systems seem to go the same route or ignore it, is to fix the sheet size. Here’s what happens:

<img width="629" alt="Bildschirmfoto 2021-06-27 um 21 30 04" src="https://user-images.githubusercontent.com/40534855/123557025-ddb6ba80-d78e-11eb-8084-74dade9a0a15.png">

As soon as I make the sheet size dynamic and the editor has a certain length of content, two scroll bars appear which make navigating the sheet really awkward. I have tried to find a solution for that for a long time, but given that even the DnD5e system has this same problem, I’m not sure that there is a solution, other than hardcoding the sheet size. But I’m not the most proficient with CSS and HTML, so maybe there is a better way. I’ll keep looking and ask on the Cypher Dev Discord.

Here’s what happens when I set .sheet-body to 100%. It basically works (with the exception of the editor above), but has the side effect of the sheet header and tab bar to scroll with the rest, as would be expected:

<img width="665" alt="Bildschirmfoto 2021-06-27 um 21 48 04" src="https://user-images.githubusercontent.com/40534855/123557492-5b7bc580-d791-11eb-8409-c652197b7a51.png">

That’s something I’d want to avoid, as that’s important information and I’d like to have that available at all times.

To be completely honest, I’m not sure that any of this will actually solve your problem. It will just delay at which point you’ll have to scroll through your lists. As for the font size and line heights, I’m hesitant to decrease those for inclusivity reasons. Some systems seem to have smaller font and that makes it harder to read for people with visual impairments. I'll look into an option for that, but I know that I can’t change the CSS file that way, so I’d have to add an HTML handlebar into each element that styles the element, I think. Not sure that’s worth the effort.

A completely different approach would be to have alternative sheets. Maybe you have an idea for layout that suits your needs better. If you have basic HTML and CSS knowledge, you could create your own sheet and register it as a module (“register” as in “register it in the system,” not necessarily as an officially listed module). I’d help you out where I can with that, but I’d rather concentrate on developing the core functions and documentation right now. Would that be something you’d be interested in? 

I’ll also ping the people on the Cypher Dev Discord, maybe someone has interest in developing different sheets. Sorry that I can’t just tell you that I have a neat solution for that. I’d love to have the character sheets resizable, but a good UX is more important to me, but I can’t deliver one with resizable windows.

**Comment by cityofkeats** [comment] 2021-06-29 02:36
That's a shame, but understandable. Thank you for the thorough explanation.

**Comment by mrkwnzl** [comment] 2021-07-11 09:13
I’ll keep looking for a solution for this, as that’s something that bothers me as well, but I’ll close this issue for now. If you happen to find a game system where the sheet size is dynamic while it avoids the issue with two scroll bars, please let me know and re-open this issue. I’d be eager to see how they did it.

**Closed by mrkwnzl** 2021-07-11 09:13 UTC
Labels: enhancement
